server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계: update / 운영: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #N+1 문제 완화
        #컬렉션 조회 최적화
        default_batch_fetch_size: 100
    # 컨트롤러에서 지연 로딩 방지
    # Service 계층에서 데이터 처리 강제
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: fitness-secret-key-very-long-fitness-secret-key-very-long
  access-token-expiration: 3600000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
